In [1]:
# Import libraries and packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy import stats

In [2]:
epa_data = pd.read_csv("c4_epa_air_quality.csv", index_col = 0)

In [3]:
# First 10 rows of the data

### YOUR CODE HERE ###
epa_data.head(10)

,date_local,state_name,county_name,city_name,local_site_name,parameter_name,units_of_measure,arithmetic_mean,aqi
0,2018-01-01,Arizona,Maricopa,Buckeye,BUCKEYE,Carbon monoxide,Parts per million,0.473684,7
1,2018-01-01,Ohio,Belmont,Shadyside,Shadyside,Carbon monoxide,Parts per million,0.263158,5
2,2018-01-01,Wyoming,Teton,Not in a city,Yellowstone National Park - Old Faithful Snow ...,Carbon monoxide,Parts per million,0.111111,2
3,2018-01-01,Pennsylvania,Philadelphia,Philadelphia,North East Waste (NEW),Carbon monoxide,Parts per million,0.300000,3
4,2018-01-01,Iowa,Polk,Des Moines,CARPENTER,Carbon monoxide,Parts per million,0.215789,3
5,2018-01-01,Hawaii,Honolulu,Not in a city,Kapolei,Carbon monoxide,Parts per million,0.994737,14
6,2018-01-01,Hawaii,Honolulu,Not in a city,Kapolei,Carbon monoxide,Parts per million,0.200000,2
7,2018-01-01,Pennsylvania,Erie,Erie,NaN,Carbon monoxide,Parts per million,0.200000,2
8,2018-01-01,Hawaii,Honolulu,Honolulu,Honolulu,Carbon monoxide,Parts per million,0.400000,5
9,2018-01-01,Colorado,Larimer,Fort Collins,Fort Collins - CSU - S. Mason,Carbon monoxide,Parts per million,0.300000,6

In [4]:
epa_data.describe()

       arithmetic_mean         aqi
count       260.000000  260.000000
mean          0.403169    6.757692
std           0.317902    7.061707
min           0.000000    0.000000
25%           0.200000    2.000000
50%           0.276315    5.000000
75%           0.516009    9.000000
max           1.921053   50.000000

In [5]:
# Sample with replacement

sampled_data = epa_data.sample(n = 50, replace = True, random_state = 42)
sampled_data

,date_local,state_name,county_name,city_name,local_site_name,parameter_name,units_of_measure,arithmetic_mean,aqi
102,2018-01-01,Texas,Harris,Houston,Clinton,Carbon monoxide,Parts per million,0.157895,2
106,2018-01-01,California,Imperial,Calexico,Calexico-Ethel Street,Carbon monoxide,Parts per million,1.183333,26
71,2018-01-01,Alabama,Jefferson,Birmingham,Arkadelphia/Near Road,Carbon monoxide,Parts per million,0.200000,2
188,2018-01-01,Arizona,Maricopa,Tempe,Diablo,Carbon monoxide,Parts per million,0.542105,10
20,2018-01-01,Virginia,Roanoke,Vinton,East Vinton Elementary School,Carbon monoxide,Parts per million,0.100000,1
102,2018-01-01,Texas,Harris,Houston,Clinton,Carbon monoxide,Parts per million,0.157895,2
121,2018-01-01,North Carolina,Mecklenburg,Charlotte,Garinger High School,Carbon monoxide,Parts per million,0.200000,2
214,2018-01-01,Florida,Broward,Davie,Daniela Banu NCORE,Carbon monoxide,Parts per million,0.273684,5
87,2018-01-01,California,Humboldt,Eureka,Jacobs,Carbon monoxide,Parts per million,0.393750,5
99,2018-01-01,California,Santa Barbara,Goleta,Goleta,Carbon monoxide,Parts per million,0.222222,3
151,2018-01-01,California,Orange,Anaheim,Anaheim,Carbon monoxide,Parts per million,0.694737,11
130,2018-01-01,California,San Bernardino,Fontana,Fontana,Carbon monoxide,Parts per million,0.626316,11
149,2018-01-01,Ohio,Franklin,Columbus,Morse Rd,Carbon monoxide,Parts per million,0.184211,3
257,2018-01-01,Kentucky,Jefferson,Louisville,CANNONS LANE,Carbon monoxide,Parts per million,0.163158,2
191,2018-01-01,Ohio,Franklin,Columbus,Smoky Row Near Road,Carbon monoxide,Parts per million,0.115789,2
160,2018-01-01,Mississippi,Hinds,Jackson,Jackson NCORE,Carbon monoxide,Parts per million,0.200000,2
21,2018-01-01,Iowa,Linn,Cedar Rapids,Public Health,Carbon monoxide,Parts per million,0.100000,1
252,2018-01-01,Ohio,Hamilton,Cincinnati,Cincinnati Near Road,Carbon monoxide,Parts per million,0.226316,3
235,2018-01-01,Pennsylvania,Lackawanna,Scranton,A420692006LAT/LON POINT IS AT CORNER OF TRAILER,Carbon monoxide,Parts per million,0.300000,3
48,2018-01-01,Florida,Hillsborough,Tampa,Munro Street (Near-Road),Carbon monoxide,Parts per million,0.347368,6
58,2018-01-01,California,Kern,Arvin,Arvin-Di Giorgio,Carbon monoxide,Parts per million,0.278947,3
169,2018-01-01,Florida,Wakulla,Saint Marks,St. Marks Wildlife Refuge,Carbon monoxide,Parts per million,0.200000,2
187,2018-01-01,Puerto Rico,Ponce,Ponce,RESIDENTIAL AREA,Carbon monoxide,Parts per million,0.336842,5
189,2018-01-01,California,Los Angeles,Pomona,Pomona,Carbon monoxide,Parts per million,1.000000,20
174,2018-01-01,Oklahoma,Adair,Cherry Tree,STILWELL,Carbon monoxide,Parts per million,0.166667,2
50,2018-01-01,Georgia,DeKalb,Not in a city,South DeKalb,Carbon monoxide,Parts per million,0.200000,2
54,2018-01-01,North Carolina,Mecklenburg,Charlotte,Remount,Carbon monoxide,Parts per million,0.200000,2
243,2018-01-01,Alaska,Fairbanks North Star,Fairbanks,NCORE,Carbon monoxide,Parts per million,0.557895,8
130,2018-01-01,California,San Bernardino,Fontana,Fontana,Carbon monoxide,Parts per million,0.626316,11
134,2018-01-01,California,Alameda,Oakland,Oakland,Carbon monoxide,Parts per million,0.600000,10
20,2018-01-01,Virginia,Roanoke,Vinton,East Vinton Elementary School,Carbon monoxide,Parts per million,0.100000,1
166,2018-01-01,New Jersey,Hudson,Jersey City,Jersey City,Carbon monoxide,Parts per million,0.133333,3
88,2018-01-01,New Jersey,Union,Elizabeth,Elizabeth Lab,Carbon monoxide,Parts per million,0.500000,6
13,2018-01-01,Arizona,Maricopa,Mesa,MESA,Carbon monoxide,Parts per million,0.505263,10
241,2018-01-01,Ohio,Preble,New Paris,Preble NCore,Carbon monoxide,Parts per million,0.176471,2
52,2018-01-01,Massachusetts,Hampden,Springfield,LIBERTY ST PARKING LOT,Carbon monoxide,Parts per million,0.210526,3
91,2018-01-01,Texas,El Paso,El Paso,El Paso Chamizal,Carbon monoxide,Parts per million,0.226316,5
34,2018-01-01,California,Fresno,Fresno,Fresno - Garland,Carbon monoxide,Parts per million,1.000000,15
205,2018-01-01,Tennessee,Shelby,Memphis,Near Road Site at Southwest Tennessee Communit...,Carbon monoxide,Parts per million,0.284211,3
80,2018-01-01,Nevada,Clark,Las Vegas,Rancho & Teddy,Carbon monoxide,Parts per million,1.036842,15
49,2018-01-01,Tennessee,Shelby,Memphis,Memphis NCORE site,Carbon monoxide,Parts per million,0.100000,1
1,2018-01-01,Ohio,Belmont,Shadyside,Shadyside,Carbon monoxide,Parts per million,0.263158,5
53,2018-01-01,South Dakota,Minnehaha,Sioux Falls,SD School for the Deaf,Carbon monoxide,Parts per million,0.242105,5
105,2018-01-01,Connecticut,New Haven,New Haven,Criscuolo Park-New Haven,Carbon monoxide,Parts per million,0.216667,3
259,2018-01-01,North Carolina,Wake,Not in a city,Triple Oak,Carbon monoxide,Parts per million,0.188889,2
190,2018-01-01,California,Madera,Madera,Madera-Pump Yard,Carbon monoxide,Parts per million,0.347368,5
217,2018-01-01,Florida,Duval,Jacksonville,Rosselle,Carbon monoxide,Parts per million,0.005263,1
43,2018-01-01,California,Contra Costa,Concord,Concord,Carbon monoxide,Parts per million,0.294444,5
161,2018-01-01,California,Kern,Bakersfield,Bakersfield-Muni,Carbon monoxide,Parts per million,0.633333,13
201,2018-01-01,Florida,Miami-Dade,Miami,Lab Annex,Carbon monoxide,Parts per million,0.305263,7